---
dependencies: []

galaxy_info:
  role_name: httpd
  author: Your Name
  description: Apache HTTP Server installation and configuration
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - web
    - apache
    - httpd
